
# You can use this file to easily send requests to your API.
# Prerequisite: humao.rest-client Vscode plugin (already present on codespace)
# High-level overview of REST API concepts used here: https://www.packtpub.com/en-us/learning/how-to-tutorials/what-are-rest-verbs-and-status-codes-tutorial?srsltid=AfmBOoppDqtkhRxj5BLZONRZFzRDmh6eP-xyTo6H4OuEHYuVbrg1d4Dm


# Requests for API endpoints of the sample project:

### Hello world endpoint: get response "Hello, Stranger!"
GET http://localhost:8080/hello-world

### Hello world with a request param passed.
# When sending the request it will ask you for the name
# hitting enter will avoid passing the param, and do the default behaviour above
# @prompt name The name to display in response
GET http://localhost:8080/hello-world
    ?name={{name}}

### Save a greeting to database
@postGreetingId = 1001
@postGreetingContent = Hello!
POST http://localhost:8080/greetings
Content-Type: application/json

{
    "id": "{{postGreetingId}}",
    "content": "{{postGreetingContent}}"
}

### Get all greetings
GET http://localhost:8080/greetings

### Get info for greeting with given content
# @prompt content Greeting content to look for, defaults to "Overview"
GET http://localhost:8080/info
    ?title={{content}}

### Update an existing greeting
@putGreetingId = 1001
@putGreetingContent = Hello again!
PUT http://localhost:8080/greetings/{{putGreetingId}}
Content-Type: application/json

{
    "content": "{{putGreetingContent}}"
}

### Delete greeting
@deleteGreetingId = 1001
DELETE http://localhost:8080/greetings/{{deleteGreetingId}}


# TODO add requests for your own endpoints!

### Register a normal user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "ioanapotlog",
  "email": "ioanapoltogg@gmail.com",
  "password": "Ioan@2003",
  "nickname": "Ioana",
  "bio": "I love cooking and baking!",
  "age": 21,
  "authorization": false,
  "vegetarian": true,
  "role": "USER"
}

### Register a chef
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "biancadogareci",
  "email": "biancadogareci@gmail.com",
  "password": "Bianc@2003",
  "nickname": "MasterChef",
  "bio": "Cooking is my passion!",
  "age": 21,
  "authorization": true,
  "vegetarian": true,
  "role": "CHEF"
}

### Login user (returns user ID instead of JWT)
@loggedInUserId = 67d82485139dba771e61a1cc
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "ioanapoltog@gmail.com",
  "password": "Ioan@2003"
}

### Change password
PUT http://localhost:8080/api/auth/change-password
Content-Type: application/json

{
  "email": "biancadogareci@gmail.com",
  "oldPassword": "Bianc@2003",
  "newPassword": "Bianc@2004"
}

### Get user
GET http://localhost:8080/api/users/get-profile/{{loggedInUserId}}

### Update user
PUT http://localhost:8080/api/users/update/{{loggedInUserId}}
Content-Type: application/json

{
  "username": "biancadogareci",
  "email": "biancadogareci@gmail.com",
  "nickname": "Lala",
  "bio": "This is an updated bio",
  "age": 18,
  "vegetarian": true
}

### Delete user
DELETE http://localhost:8080/api/users/delete/{{loggedInUserId}}



### RECIPE

### Add a new recipe
POST http://localhost:8080/api/recipes/add
Content-Type: application/json

{
  "userId": "{{loggedInUserId}}",
  "name": "Vanilla Cake",
  "description": "A delicious chocolate cake.",
  "photo": "https://chocolate-cake.jpg",
  "category": "Dessert",
  "type": "Food",
  "vegetarian": true,
  "frozen": false,
  "favoriteCount": 0
}

### Add a new recipe
POST http://localhost:8080/api/recipes/add
Content-Type: application/json

{
  "userId": "{{loggedInUserId}}",
  "name": "Martini",
  "description": "A delicious drink.",
  "photo": "https://chocolate-cake.jpg",
  "category": "Cocktail",
  "type": "Alcoholic-Drink",
  "vegetarian": true,
  "frozen": false,
  "favoriteCount": 0
}

### Add a new recipe
POST http://localhost:8080/api/recipes/add
Content-Type: application/json

{
  "userId": "{{loggedInUserId}}",
  "name": "Meat",
  "description": "A delicious meal.",
  "photo": "https://chocolate-cake.jpg",
  "category": "Meal",
  "type": "Food",
  "vegetarian": false,
  "frozen": false,
  "favoriteCount": 0
}

### Change frozen status (Toggle)
@recipeId = 67d823ba139dba771e61a1cb
POST http://localhost:8080/api/recipes/change-status/{{recipeId}}?userId={{loggedInUserId}}

### Get Recipes (Filtered)
GET http://localhost:8080/api/recipes/get-recipes/{{loggedInUserId}}

### Get Recipe by ID (with user ID)
GET http://localhost:8080/api/recipes/get-recipe/{{recipeId}}?userId={{loggedInUserId}}

### Update Recipe
PUT http://localhost:8080/api/recipes/update/{{recipeId}}?userId={{loggedInUserId}}
Content-Type: application/json

{
  "name": "Vanillaaa Cake",
  "description": "Aaaa delicious chocolate cake.",
  "photo": "https://chocolate-cake.jpg",
  "category": "Desserttttt",
  "type": "Food",
  "vegetarian": true,
  "frozen": false
}

### Delete Recipe
DELETE http://localhost:8080/api/recipes/delete/{{recipeId}}?userId={{loggedInUserId}}

### Get weekly
GET http://localhost:8080/api/recipes/featured/{{loggedInUserId}}

### Follow user
@userIdToFollow = 67d7339be9a5b42f61e2d082

### Add to favorites
POST http://localhost:8080/api/recipes/add-to-favorites/{{recipeId}}?userId={{loggedInUserId}}

### Remove from favorites 
DELETE http://localhost:8080/api/recipes/remove-from-favorites/{{recipeId}}?userId={{loggedInUserId}}
