
# You can use this file to easily send requests to your API.
# Prerequisite: humao.rest-client Vscode plugin (already present on codespace)
# High-level overview of REST API concepts used here: https://www.packtpub.com/en-us/learning/how-to-tutorials/what-are-rest-verbs-and-status-codes-tutorial?srsltid=AfmBOoppDqtkhRxj5BLZONRZFzRDmh6eP-xyTo6H4OuEHYuVbrg1d4Dm

# @loggedInUserId = 681a75c4cecc38136bfb0d54
@loggedInUserId = 681b017738234d17996be937

@recipeId = 680ff9d1796b7b40f6badbb5
@userIdToFollow = 67d7339be9a5b42f61e2d082
@commentId = 67d83fa5944b994e397a3965
@chefId =  67d83e7d944b994e397a395c

### Register a normal user (18+, vegetarian)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "ioanapotlog",
  "email": "ioanapoltog@gmail.com",
  "password": "Ioan@2003",
  "nickname": "Ioana",
  "bio": "I love cooking and baking!",
  "age": 21,
  "authorization": false,
  "vegetarian": true,
  "role": "USER"
}

### Register a normal user (18+, non-vegetarian)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "andreeacapitanu",
  "email": "andreeacapitanu@gmail.com",
  "password": "Andree@2003",
  "nickname": "Andreea",
  "bio": "I love cooking!",
  "age": 30,
  "authorization": false,
  "vegetarian": false,
  "role": "USER"
}

### Register a normal user (underage, vegetarian)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "mariapop",
  "email": "mariapop@gmail.com",
  "password": "Mari@2003",
  "nickname": "Maria",
  "bio": "I am new here!",
  "age": 17,
  "authorization": false,
  "vegetarian": true,
  "role": "USER"
}

### Register a chef
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "biancadogareci",
  "email": "biancadogareci@gmail.com",
  "password": "Bianc@2003",
  "nickname": "MasterChef",
  "bio": "Cooking is my passion!",
  "age": 21,
  "authorization": true,
  "vegetarian": true,
  "role": "CHEF"
}

### Register a chef
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "anamaria",
  "email": "anamaria@gmail.com",
  "password": "An@20032003",
  "nickname": "ChefdeChef",
  "bio": "Cooking is my passion!",
  "age": 21,
  "authorization": true,
  "vegetarian": true,
  "role": "CHEF"
}

### Login user (returns user ID instead of JWT)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "biancadogareci@gmail.com",
  "password": "Bianc@2003"
}

### Change password
PUT http://localhost:8080/api/auth/change-password
Content-Type: application/json

{
  "email": "biancadogareci@gmail.com",
  "oldPassword": "Bianc@2003",
  "newPassword": "Bianc@2004"
}

### Get user
GET http://localhost:8080/api/users/get-profile/{{loggedInUserId}}

### Update user
PUT http://localhost:8080/api/users/update/{{loggedInUserId}}
Content-Type: application/json

{
  "username": "biancadogareci",
  "email": "biancadogareci@gmail.com",
  "nickname": "Lala",
  "bio": "This is an updated bio",
  "age": 18,
  "vegetarian": true
}

### Delete user
DELETE http://localhost:8080/api/users/delete/{{loggedInUserId}}

### Follow user
POST http://localhost:8080/api/users/follow/{{userIdToFollow}}?followerId={{loggedInUserId}}



### RECIPE

### Add a new recipe
POST http://localhost:8080/api/recipes/add
Content-Type: application/json

{
  "userId": "{{loggedInUserId}}",
  "name": "Vanilla Cake",
  "description": "A delicious chocolate cake.",
  "photo": "https://chocolate-cake.jpg",
  "category": "Dessert",
  "type": "Food",
  "vegetarian": true
}

### Add a new recipe
POST http://localhost:8080/api/recipes/add
Content-Type: application/json

{
  "userId": "{{loggedInUserId}}",
  "name": "Martini",
  "description": "A delicious drink.",
  "photo": "https://chocolate-cake.jpg",
  "category": "Cocktail",
  "type": "Alcoholic-Drink",
  "vegetarian": true
}

### Add a new recipe
POST http://localhost:8080/api/recipes/add
Content-Type: application/json

{
  "userId": "{{loggedInUserId}}",
  "name": "Meat",
  "description": "A delicious meal.",
  "photo": "https://chocolate-cake.jpg",
  "category": "Meal",
  "type": "Food",
  "vegetarian": false
}

### Change frozen status (Toggle)
POST http://localhost:8080/api/recipes/change-status/{{recipeId}}?userId={{loggedInUserId}}

### Get Recipes (Filtered)
GET http://localhost:8080/api/recipes/get-recipes/{{loggedInUserId}}

### Get Recipe by ID (with user ID)
GET http://localhost:8080/api/recipes/get-recipe/{{recipeId}}?userId={{loggedInUserId}}

### Get recipes by category sorted by popularity
GET http://localhost:8080/api/recipes/category?category=Cocktail

### Get recipes from followed chefs
GET http://localhost:8080/api/recipes/get-recipes-by-followed-chefs?userId={{loggedInUserId}}

### Update Recipe
PUT http://localhost:8080/api/recipes/update/{{recipeId}}?userId={{loggedInUserId}}
Content-Type: application/json

{
  "name": "Vanillaaa Cake",
  "description": "Aaaa delicious chocolate cake.",
  "photo": "https://chocolate-cake.jpg",
  "category": "Desserttttt",
  "type": "Food",
  "vegetarian": true,
  "frozen": false
}

### Delete Recipe
DELETE http://localhost:8080/api/recipes/delete/{{recipeId}}?userId={{loggedInUserId}}

### Get featured
GET http://localhost:8080/api/recipes/featured/{{loggedInUserId}}

### Add a contributor (valid chef -> authorized chef with at least 3 recipes posted and a following of 2 and 18+)
POST http://localhost:8080/api/recipes/add-contributor?loggedInUserId={{loggedInUserId}}&chefId={{chefId}}&recipeId={{recipeId}}
Content-Type: application/json

### Remove a contributor (only if logged-in user is the recipe owner)
DELETE http://localhost:8080/api/recipes/remove-contributor?loggedInUserId={{loggedInUserId}}&chefId={{chefId}}&recipeId={{recipeId}}
Content-Type: application/json

### Add to favorites
POST http://localhost:8080/api/recipes/add-to-favorites/{{recipeId}}?userId={{loggedInUserId}}

### Remove from favorites 
DELETE http://localhost:8080/api/recipes/remove-from-favorites/{{recipeId}}?userId={{loggedInUserId}}

### Add a Comment
POST http://localhost:8080/api/comments/add?userId={{loggedInUserId}}&recipeId={{recipeId}}
Content-Type: application/json

"This recipe is amazing!!"

### Add a second Comment
POST http://localhost:8080/api/comments/add?userId={{loggedInUserId}}&recipeId={{recipeId}}
Content-Type: application/json

"This recipe is ok!!"

### Get Comments for a Recipe
GET http://localhost:8080/api/comments/get/{{recipeId}}

### Update a Comment
PUT http://localhost:8080/api/comments/update/{{commentId}}?userId={{loggedInUserId}}
Content-Type: application/json

"I changed my mind, this recipe is legendary!"

### Delete a Comment
DELETE http://localhost:8080/api/comments/delete/{{commentId}}?userId={{loggedInUserId}}

### Like a Comment
POST http://localhost:8080/api/comments/like/{{commentId}}?userId={{loggedInUserId}}

### Unlike a Comment
POST http://localhost:8080/api/comments/unlike/{{commentId}}?userId={{loggedInUserId}}

### Report a Comment
POST http://localhost:8080/api/comments/report/{{commentId}}?userId={{loggedInUserId}}

