pipeline {
    agent any
    tools {
        jdk 'jdk21' // This name must match the JDK installation name used in Jenkins Global Tool Configuration
    }

    environment {
        DOCKER_CREDENTIALS = credentials("docker_password")
        GITHUB_TOKEN = credentials("github_token")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Tag image') {
            steps {
                script {
                    sh([script: 'git fetch --tag', returnStdout: true]).trim()
                    def MAJOR_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 1', returnStdout: true]).trim()
                    def MINOR_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 2', returnStdout: true]).trim()
                    def PATCH_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 3', returnStdout: true]).trim()
                    def IMAGE_TAG = "${MAJOR_VERSION}.${(MINOR_VERSION.toInteger() + 1)}.${PATCH_VERSION}"

                    // Build and push image
                    sh "docker build -t ${DOCKER_CREDENTIALS_USR}/hello-img:${IMAGE_TAG} ."
                    sh "echo \$DOCKER_CREDENTIALS_PSW | docker login docker.io -u \$DOCKER_CREDENTIALS_USR --password-stdin"
                    sh "docker push ${DOCKER_CREDENTIALS_USR}/hello-img:${IMAGE_TAG}"

                    // Tag in Git
                    sh "git tag ${IMAGE_TAG}"
                    withCredentials([string(credentialsId: 'github_token', variable: 'GITHUB_TOKEN')]) {
                        sh "git push https://\$GITHUB_TOKEN@github.com/BiancaDogareci/service.git refs/tags/${IMAGE_TAG}"
                    }

                    // Export IMAGE_TAG to env so next stage can use it
                    env.IMAGE_TAG = IMAGE_TAG
                }
            }
        }

        stage('Run Containers') {
            steps {
                sh 'IMAGE_TAG=${IMAGE_TAG} docker compose up -d hello mongo'
            }
        }

    }
}
