pipeline {
    agent any
    tools {
        jdk 'jdk21' // This name must match the JDK installation name used in Jenkins Global Tool Configuration
    }

    environment {
        DOCKER_CREDENTIALS = credentials("docker_password")
        GITHUB_TOKEN = credentials("github_token")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Tag image') {
            steps {
                script {
                    sh([script: 'git fetch --tag', returnStdout: true]).trim()
                    env.MAJOR_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 1', returnStdout: true]).trim()
                    env.MINOR_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 2', returnStdout: true]).trim()
                    env.PATCH_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 3', returnStdout: true]).trim()
                    env.IMAGE_TAG = "${env.MAJOR_VERSION}.\$((${env.MINOR_VERSION} + 1)).${env.PATCH_VERSION}"

                    // GIT_TAG = sh([script: 'git fetch --tag && git tag', returnStdout: true]).trim()
                    // MAJOR_VERSION = sh([script: 'git tag | cut -d . -f 1', returnStdout: true]).trim()
                    // MINOR_VERSION = sh([script: 'git tag | cut -d . -f 2', returnStdout: true]).trim()
                    // PATCH_VERSION = sh([script: 'git tag | cut -d . -f 3', returnStdout: true]).trim()
                    // IMAGE_VERSION = "${MAJOR_VERSION}.$((MINOR_VERSION.toInteger() + 1)).${PATCH_VERSION}"

                    sh "docker build -t ${DOCKER_CREDENTIALS_USR}/hello-img:${IMAGE_VERSION} ."
                    sh "echo \$DOCKER_CREDENTIALS_PSW | docker login docker.io -u \$DOCKER_CREDENTIALS_USR --password-stdin"
                    sh "docker push ${DOCKER_CREDENTIALS_USR}/hello-img:${IMAGE_VERSION}"

                    // sh "docker build -t biancadogareci/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION} ."
                    // sh "docker login docker.io -u biancadogareci -p Bianca_2003"
                    // sh "docker push biancadogareci/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION}"

                    sh "git tag ${env.IMAGE_TAG}"
                    sh "git push https://${GITHUB_TOKEN}@github.com/${DOCKER_PASSWORD_USR}/service.git ${env.IMAGE_TAG}"
                }
            }
        }

        stage('Run Containers') {
            steps {
                sh 'IMAGE_TAG=${IMAGE_TAG} docker compose up -d hello mongo'
            }
        }

    }
}
